# Generated by Django 4.2.7 on 2024-01-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('investment', models.PositiveIntegerField()),
                ('daily_earning', models.PositiveIntegerField()),
                ('products', models.PositiveIntegerField()),
                ('per_product_earning', models.PositiveIntegerField()),
                ('daily_earning_balance', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('url', models.SlugField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='f56903bf4785420fa0351f931d41f5ae', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trx_id',
            field=models.ImageField(default='400.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='main.plan'),
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
