# Generated by Django 4.2.7 on 2024-01-29 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_line_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=1, help_text='1 Means Minimum Rating, while 5 means Maximum Rating', validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='916ee86d0b0444c48c953159ac3ec194', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.product'),
        ),
    ]
