# Generated by Django 4.2.7 on 2024-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_alter_customuser_invite_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='9d0834c6deb945a2b4a1694443fca6e2', max_length=50),
        ),
    ]
