# Generated by Django 4.2.7 on 2024-01-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='400.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='84c9733c17594440af957da4f2e3eed6', max_length=50),
        ),
    ]
