# Generated by Django 4.2.7 on 2024-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_image_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trx', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='7605fe1146504f8bb11ede2d5b741c04', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transctions',
            field=models.ManyToManyField(related_name='transactions', to='main.transctions'),
        ),
    ]
