# Generated by Django 4.2.7 on 2024-01-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_transctions_alter_customuser_invite_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=16)),
                ('billing_state', models.CharField(choices=[('EasyPaisa', 'EasyPaisa'), ('JazzCash', 'JazzCash')], max_length=20)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='c48d12e762b5449b94850c9ce8ca1fc4', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='withdrawalrequests',
            field=models.ManyToManyField(related_name='withdrawalrequests', to='main.withdrawalrequest'),
        ),
    ]
