# Generated by Django 4.2.7 on 2024-01-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_withdrawalrequest_alter_customuser_invite_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='d0e06169cc6e49088766e6594cc4d126', max_length=50),
        ),
    ]
