# Generated by Django 4.2.7 on 2024-01-30 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_balance_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referrals',
            field=models.ManyToManyField(related_name='referrers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='3d2f47d237bd4c588de79d532fa6c49d', max_length=50),
        ),
    ]
