# Generated by Django 4.2.7 on 2024-01-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_referrals_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='c26a353710b74c779a8c8212c2bb216f', max_length=50),
        ),
    ]
