# Generated by Django 4.2.7 on 2024-01-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_rank_level_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='caa80e3b4c3c4923a4cf690e4662e748', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank_level',
            field=models.IntegerField(default=0),
        ),
    ]
