# Generated by Django 4.2.7 on 2024-02-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_customuser_on_dashboard_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='Unknown_person.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='29374eb4d0ac44ef81972570f3d7e6c5', max_length=50),
        ),
    ]
