# Generated by Django 4.2.7 on 2024-02-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser_image_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='topic',
            field=models.CharField(default='wallet', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='c2f5f98305d94ba2b7529ac64707261d', max_length=50),
        ),
    ]
