# Generated by Django 4.2.7 on 2024-02-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_withdrawalrequest_topic_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='a9a1e91b5e7e41a98f8edb9322a4b3e6', max_length=50),
        ),
    ]
