# Generated by Django 4.2.7 on 2024-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_withdrawalrequest_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('url', models.URLField(max_length=1200)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='link_earning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='792ba52489024e09a3d1c04a80b6feb0', max_length=50),
        ),
    ]
