# Generated by Django 4.2.7 on 2024-02-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_links_plan_link_earning_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='click_on_link1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='click_on_link2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='click_on_link3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='click_on_link4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links', to='main.links'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='3d4ca767c04147c099209161cafccf81', max_length=50),
        ),
    ]
