# Generated by Django 4.2.7 on 2024-02-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_customuser_reward_earning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='03270485632', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='133357b1d6e249e9bb3f8a3c71527fc6', max_length=50),
        ),
    ]
