# Generated by Django 4.2.7 on 2024-02-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_payment_alter_customuser_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_link',
            field=models.CharField(default='a3de4749c1e64edd923c91b24df2532d', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank_level',
            field=models.IntegerField(default=1),
        ),
    ]
